<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <StaticWebAssetBasePath>/</StaticWebAssetBasePath>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>UmbMediaSqueeze</PackageId>
    <Product>UmbMediaSqueeze</Product>
    <Title>UmbMediaSqueeze</Title>
    <Version>1.0.0</Version>
    <PackageTags>umbraco;umbraco-marketplace;media-utils</PackageTags>
    <Authors>Stelios Zisis</Authors>
    <PackageProjectUrl>https://github.com/nightriderjt/UmbMediaSqueeze</PackageProjectUrl>
    <RepositoryUrl>https://github.com/nightriderjt/UmbMediaSqueeze</RepositoryUrl>
    <PackageIcon>umbMediaSqueezeLogo.png</PackageIcon>
  </PropertyGroup>


  <!-- Central package management - no versions -->
  <ItemGroup>
    <PackageReference Include="Umbraco.Cms.Api.Common" />
    <PackageReference Include="Umbraco.Cms.Api.Management" />
    <PackageReference Include="Umbraco.Cms.Web.Common" />
    <PackageReference Include="Umbraco.Cms.Web.Website" />
  </ItemGroup>


  <ItemGroup>
    <!-- Dont include the client folder as part of packaging nuget build -->
    <Content Remove="Client\**" />

    <!-- However make the Umbraco-package.json included for dotnet pack or nuget package and visible to the solution -->
    <None Include="Client\public\umbraco-package.json" Pack="false" />
    <None Include="README.md" Pack="true" PackagePath="" />
    <None Include="Client\public\assets\umbMediaSqueezeLogo.png" Pack="true" PackagePath="" /> 
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  
</Project>
